# Generated by Django 3.1.2 on 2021-03-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmodel',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
