# Generated by Django 3.1.2 on 2021-03-25 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0002_auto_20210325_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmodel',
            name='template',
        ),
        migrations.AddField(
            model_name='mailmodel',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mailmodel',
            name='subject',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mailmodel',
            name='to_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mailmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
