# Generated by Django 3.1.2 on 2021-03-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201014_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
