# Generated by Django 3.1.2 on 2021-03-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_default_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=320, null=True, verbose_name='Email Address'),
        ),
    ]
